format_version: 3
pipelines:
  "gocd-s3-artifact-plugin":
    group: gocd
    label_template: "${git[:8]}"
    locking: off
    materials:
      git:
        type: configrepo
        blacklist:
          - "*.md"
          - "build.gradle"
    secure_variables:
      VAULT_TOKEN: "AES:am1B7EuHGEV67+WKsAqzRQ==:AU2HecWwVR2T2OqyNN4D7+9DYWZQ3udAXXp8fnR8jjk="
    stages:
      - build:
          clean_workspace: true
          elastic_profile_id: w.c2.m2048.e10
          artifacts:
           - build:
               source: build/libs/*.jar*
               destination: build/libs
          tasks:
           - exec:
               command: bash
               arguments:
                - -c
                - ./tasks tf_apply create
           - exec:
               command: bash
               arguments:
                - -c
                - ./tasks build_test
           - exec:
               run_if: any
               command: bash
               arguments:
                - -c
                - ./tasks tf_apply destroy
      - release:
          approval: manual
          clean_workspace: true
          jobs:
            github:
              elastic_profile_id: w.c2.m2048.e10
              tasks:
                - fetch:
                    stage: build
                    job: build
                    source: build/libs
                    destination: build
                - exec:
                    command: /bin/bash
                    arguments:
                      - ./tasks
                      - github_release
      - bump:
          clean_workspace: true
          jobs:
            patch:
              elastic_profile_id: w.c2.m2048.e10
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks bump
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks commit
                - exec:
                    command: git
                    arguments:
                      - push
                      - origin
                      - master
